PROC IMPORT OUT= WORK.Cam 
            DATAFILE= "C:\Users\tpatel6\Desktop\SAS\listings Cambridge (
2).csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 

	 data WORK.Cam;
   set Cam; 
   /* Create dummy variables for room_type */
   if room_type = 'Entire home/apt' then do;
      entire_home = 1;
      private_room = 0;
      shared_room = 0;
   end;
   else if room_type = 'Private room' then do;
      entire_home = 0;
      private_room = 1;
      shared_room = 0;
   end;
   else if room_type = 'Shared room' then do;
      entire_home = 0;
      private_room = 0;
      shared_room = 1;
   end;
   else do;
      entire_home = 0;
      private_room = 0;
      shared_room = 0;
   end;
/* Create dummy variables for Neighbourhood */
   if neighbourhood = 'West Cambridge' then do;
      West_Cambridge = 1;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	 end;
   else if neighbourhood = 'East Cambridge' then do;
      West_Cambridge = 0;
      East_Cambridge = 1;
      Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
   end;
   else if neighbourhood = 'Agassiz' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 1;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	 end;
	 else if neighbourhood = 'Mid-Cambridge' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 1;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	 end;
	 else if neighbourhood = 'North Cambridge' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 1;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	end;
	 else if neighbourhood = 'Riverside' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 1;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	end;
	 else if neighbourhood = 'The Port' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 1;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	end;
	else if neighbourhood = 'Cambridgeport' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 1;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
	end;
	else if neighbourhood = 'Neighborhood Nine' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 1;
	  Cambridge_Highlands = 0;
	end;
	else if neighbourhood = 'Cambridge Highlands' then do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 1;
	end;
   else do;
      West_Cambridge = 0;
      East_Cambridge = 0;
	  Agassiz = 0;
	  Mid_Cambridge = 0;
	  North_Cambridge = 0;
	  Riverside = 0;
	  The_Port = 0;
	  Cambridgeport = 0;
	  Neighborhood_Nine = 0;
	  Cambridge_Highlands = 0;
   end;

      /*  Generate Summary Statistics for Key Variables */
  proc means data=WORK.Cam N Mean StdDev Min Max;
   var price entire_home private_room shared_room minimum_nights number_of_reviews 
       availability_365 reviews_per_month longitude last_review 
       calculated_host_listings_count number_of_reviews_ltm West_Cambridge East_Cambridge Agassiz Mid_Cambridge North_Cambridge Riverside The_Port Cambridgeport Neighborhood_Nine Cambridge_Highlands;
proc reg data=WORK.Cam;
   model price = entire_home private_room shared_room minimum_nights number_of_reviews reviews_per_month availability_365 longitude 
number_of_reviews_ltm last_review calculated_host_listings_count West_Cambridge East_Cambridge Agassiz Mid_Cambridge North_Cambridge Riverside The_Port Cambridgeport Neighborhood_Nine Cambridge_Highlands;


RUN;
